# Generated by Django 3.2.8 on 2021-12-23 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_productsmodel_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutrientsmodel',
            name='base',
        ),
    ]
