# Generated by Django 3.2.8 on 2021-12-24 02:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_remove_nutrientsmodel_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutrientsmodel',
            name='base',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='nutrients', to='app.productsmodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL),
        ),
    ]
